### PR TITLE
Depend on matplotlib-base to avoid pyqt dependency

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

For my personal motivation, see [this comment](https://github.com/jupyter/docker-stacks/pull/896#issuecomment-515888808)

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Sorry, I am new to this. I'm just trying to fix a stray dependency. I might have misunderstood something about the license file. Any guidance would be appreciated. (Also, I am traveling at the moment, so my availability may be limited.)

**Comment by maresb** [comment]
There's apparently no license file in the source, so I had to revert.  Sorry about the noise.

**Comment by ocefpaf** [comment]
Thanks @maresb!

**Pull request merged**
